#apiVersion: v1
#kind: Namespace
#metadata:
#  name: hackathon
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pseudocode-ui
  namespace: hackathon
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pseudocode-ui
  template:
    metadata:
      labels:
        app: pseudocode-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: pseudocode-ui-app
          image: 'rameshm2020/hackathon:pseudocode-ui.14'
#          imagePullSecrets:
#          - name: regcred
          imagePullPolicy: Always
          resources:
            requests:
              memory: 400Mi
              cpu: '0.5'
            limits:
              memory: 800Mi
              cpu: '0.8'

