apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80
      nodeSelector:
              #              beta.kubernetes.io/os: linux
          node-role.kubernetes.io/master: ""
      tolerations:
  # Allow this pod to run on the master.
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
